mysite/main/urls.py
from django.urls import path
from . import views

app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('', views.HomePage.as_view(), name="homepage"),
    path('login', views.LoginPageView.as_view(), name='login'),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("logout", views.UserLogoutView.as_view(), name="logout"),
    path('Djelatnik', views.DjelatnikList.as_view(), name='DjelatnikList'),
    path('Prostorija', views.ProstorijaList.as_view(), name='ProstorijaList'),
    path('Oprema', views.OpremaList.as_view(), name='OpremaList'),
    path('Rezervacija', views.RezervacijaList.as_view(), name='RezervacijaList'),

    path('rezervacije', views.RezervacijaListView.as_view(), name='all'),
    path('rezervacije/<int:pk>/', views.RezervacijaDetailView.as_view(), name='rezervacije_detail'),
    path('rezervacije/create/', views.RezervacijaCreateView.as_view(), name='rezervacije_create'),
    path('rezervacije/<int:pk>/update/', views.RezervacijaUpdateView.as_view(), name='rezervacije_update'),
    path('rezervacije/<int:pk>/delete/', views.RezervacijaDeleteView.as_view(), name='rezervacije_delete'), 
]


mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('', include('main.urls')), 
    path('admin/', admin.site.urls),
]

mysite/main/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.core.exceptions import ValidationError

# Create your models here.
class Djelatnik(AbstractUser):

    username = None
    Ime = models.CharField(max_length=100)
    Prezime = models.CharField(max_length=100)
    OIB = models.IntegerField(
        validators=[MinValueValidator(10000000000), MaxValueValidator(99999999999)],
    null=True)
    email = models.EmailField(unique=True)
    titule_lista = [("PR", "Profesor"), ("AS", "Asistent")]
    titula = models.CharField(max_length=100, choices=titule_lista)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.Ime


class Prostorija(models.Model):
    Broj_prostorije = models.CharField(max_length=100)
    Kat = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(7)])

    def __str__(self):
        return self.Broj_prostorije


class Oprema(models.Model):
    Ime_opreme = models.CharField(max_length=100)
    Cijena_opreme = models.DecimalField(max_digits=10, decimal_places=2)
    Prostorija = models.ForeignKey(Prostorija, on_delete=models.CASCADE)

    def __str__(self):
        return self.Ime_opreme


class Rezervacija(models.Model):
    Djelatnik = models.ForeignKey(Djelatnik, on_delete=models.CASCADE)
    Oprema = models.ForeignKey(Oprema, on_delete=models.CASCADE)
    Prostorija = models.ForeignKey(Prostorija, on_delete=models.CASCADE)
    Razdoblje_od = models.DateField()
    Razdoblje_do = models.DateField()

    def __str__(self):
        return "%s %s %s %s %s %s %s" % (
            self.Djelatnik,
            "rezervacija. Od",
            self.Razdoblje_od,
            "do",
            self.Razdoblje_do,
            ". Prostorija",
            self.Prostorija,
        )

    def clean(self, *args, **kwargs):
        if self.Oprema.Prostorija != self.Prostorija:
            raise ValidationError("Oprema se ne nalazi u prostoriji.")

        Razdoblje_od_in_range = models.Q(Razdoblje_od__lte=self.Razdoblje_od, Razdoblje_do__gte=self.Razdoblje_od)
        Razdoblje_do_in_range = models.Q(Razdoblje_od__lte=self.Razdoblje_do, Razdoblje_do__gte=self.Razdoblje_do)
        # Queryset that finds all clashing timeslots with the same day
        queryset = self._meta.default_manager.filter(Razdoblje_od_in_range | Razdoblje_do_in_range)
        if self.pk:
            queryset = queryset.exclude(pk=self.pk) # Exclude this object if it is already saved to the database
        if queryset.exists():
            raise ValidationError('An existing timeslot clashes with the given one!') 

        super().clean(*args, **kwargs)

    


    
    @property
    def sazetak(self):
        return str(self)

mysite/main/forms.py
# import form class from django
from django import forms  
from django.contrib.auth.forms import UserCreationForm

# import GeeksModel from models.py
from .models import Djelatnik, Prostorija, Oprema, Rezervacija
  
# create a ModelForm

class DjelatnikCreationForm(UserCreationForm):
    
    class Meta:
        model = Djelatnik
        fields = ["Ime", "Prezime", "OIB", "email", "titula"]
        
class DjelatnikLoginForm(forms.ModelForm):

    class Meta:
        model = Djelatnik
        fields = ["email", "password"]

mysite/main/views.py
from django.views.generic import TemplateView
from django.views.generic import ListView, CreateView
from django.views.generic import View
from main.models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .forms import DjelatnikLoginForm, DjelatnikCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView




class HomePage(TemplateView):
    template_name = 'base.html'
    form = DjelatnikLoginForm
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse("main:all"))
        return super(HomePage, self).dispatch(request, *args, **kwargs)


class DjelatnikList(ListView):
    template_name = 'main/djelatnik_list.html'
    model = Djelatnik

class ProstorijaList(ListView):
    model = Prostorija

class OpremaList(ListView):
    model = Oprema

class RezervacijaList(ListView):
    model = Rezervacija

class LoginPageView(LoginView):
    template_name = 'authentication/login.html'
    next_page = "/"
    
class UserLogoutView(LogoutView):
    next_page = "/"
    def signout(request):
        logout(request)
        
class SignUpView(CreateView):
    form_class = DjelatnikCreationForm
    next_page = "/login"
    template_name = "authentication/signup.html"
    success_url = "/login"



class RezervacijaBaseView(LoginRequiredMixin, View):
    model = Rezervacija
    fields = '__all__'
    success_url = reverse_lazy('main:all')
    login_url = '/login'
    #redirect_field_name = 'redirect_to'

class RezervacijaListView(RezervacijaBaseView, ListView):
    """View to list all films.
    Use the 'film_list' variable in the template
    to access all Film objects"""

class RezervacijaDetailView(RezervacijaBaseView, DetailView):
    template_name = 'main/rezervacija_detail.html'
    """View to list the details from one film.
    Use the 'film' variable in the template to access
    the specific film here and in the Views below"""

class RezervacijaCreateView(RezervacijaBaseView, CreateView):
    """View to create a new film"""

    

class RezervacijaUpdateView(RezervacijaBaseView, UpdateView):
    """View to update a film"""

class RezervacijaDeleteView(RezervacijaBaseView, DeleteView):
    """View to delete a film""" 

mysite/main/templates/authentication/login.html
{% extends "base.html" %}

{% block content %}

<form method="POST">{% csrf_token %}
    
<!-- form variable -->    
 {{ form.as_p }} 

  <input type="submit" name="sumbit">
</form>

{% endblock %} 

mysite/main/templates/authentication/signup.html
{% extends "base.html" %}

{% block content %}
<h2>Sign Up</h2>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock content %}

mysite/main/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block title %}{% endblock title %}
  </head>
  <body>
    <h1>Rezervacija Prostorija i opreme</h1>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mysite/main/templates/main/djelatnik_list.html
{% extends "base.html" %}
{% block content %}
<br>
<h2> Djelatnik </h2>
<br>
{% for Djelatnik in djelatnik_list %}
<div class="Djelatnik">
    <h4>{{ Djelatnik.Ime }}</h4>
</div>
{% endfor %}
{% endblock %}

mysite/main/templates/main/homepage.html
{% extends "index.html" %}
{% block content %}
<h1>Homepage</h1>
{% endblock %}

mysite/main/templates/main/oprema_list.html
{% extends "base.html" %}
{% block content %}
<br>
<h2> Oprema </h2>
<br>
{% for Oprema in oprema_list %}
<div class="Oprema">
    <h4>{{ Oprema.Ime_opreme }}</h4>
</div>
{% endfor %}
{% endblock %}

mysite/main/templates/main/prostorija_list.html
{% extends "base.html" %}
{% block content %}
<br>
<h2> Prostorija </h2>
<br>
{% for Prostorija in prostorija_list %}
<div class="Prostorija">
    <h4>{{ Prostorija.Broj_prostorije }}</h4>
</div>
{% endfor %}
{% endblock %}

mysite/main/templates/main/rezervacija_confirm_delete.html
{% extends "base.html" %}

{% block content %}

{% url 'main:rezervacije' as list_all %}

<div class="container d-flex justify-content-center mt-5" style="width: 50%;">
    <div class="col mt-5 text-center">
        <h1 class="mb-5">Brisanje rezervacije</h1>

        <p class="h5">Jeste li sigurni da želite obrisati rezervaciju?</p>
        <h3 class="my-5">{{ rezervacija.sazetak }}</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-lg" value="Potvrdi" style="margin-right: 30px; margin-top: 30px;">
            <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location={{ list_all }}; return false;" value="Odustani">
        </form>
    </div>
</div>

{% endblock %}

mysite/main/templates/main/rezervacija_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Detalji rezervacije</h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in rezervacija.meta.get_fields  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endfor %}

                    
                    Rezervacija: {{rezervacija.Djelatnik}}<br/>
                    {{rezervacija.Oprema}}<br/>
                    
                    
                        
                </tbody>
            </table>
        </div>

        <div class="d-flex justify-content-center">
            <a href="{% url 'main:all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

mysite/main/templates/main/rezervacija_form.html
{% extends "base.html" %}

{% block content %}

<!-- BOOTSTRAP FORM -->

<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Potvrdi" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url 'main:all' %}'; return false;" value="Odustani">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %} 

mysite/main/templates/main/rezervacija_list.html
{% extends 'base.html' %}

{% block content %}
{% for rezervacija in rezervacija_list %}
    {% for colname in rezervacija.column_set.all  %}
        <p>{{colname}}</p>
    {% endfor %}
{% endfor %}


<div class="container d-flex mt-5" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Rezervacije</h1>
        <table class="table table-bordered table-hover mt-5">
            <thead>
                <tr>
                    {% comment %} <th>#</th> {% endcomment %}
                    <th class="text-center" scope="col">Rezervacija</th>
                    <th class="text-center" scope="col">Opis</th>
                    <th class="text-center" scope="col">Ažuriraj</th>
                    <th class="text-center" scope="col">Obriši</th>
                    
                </tr>
            </thead>
            <tbody>
            
                {% for rezervacija in rezervacija_list %}
                <tr>
                    {% comment %} <th scope="row">{{forloop.counter}}</th> {% endcomment %}
                    <td class="ml-5"><a href= {% url "main:rezervacije_detail" rezervacija.pk %} >{{rezervacija.Djelatnik}}</a></td>
                    <td class="text-center">{{rezervacija.sazetak}}</td>
                    <td><a href={% url "main:rezervacije_update" rezervacija.id %} >Update</a></td>
                    <td><a href={% url "main:rezervacije_delete" rezervacija.id %} >Delete</a></td>
                </tr>
            {% endfor %}
        
            </tbody>
        </table>    
        <div class="d-flex justify-content-center">
            <a href="{% url 'main:rezervacije_create' %}" class="d-block btn btn-primary btn-lg my-5">Napravi rezervaciju</a>
        </div>
    </div>
        
</div>

{% endblock content %} 

mysite/main/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul>
    {% if user.is_authenticated %}
    <li>Pozdrav {{ user.email }}!</li>
    <li><a href={% url 'main:logout' %}>Odjava</a></li>
    {% else %}
    <li>Niste prijavljeni.</li>
    <li><a href={% url 'main:login' %}>Prijava</a> | <a href={% url 'main:signup' %}>Registracija</a></li>
    {% endif %}
    </ul>
</nav>